name: Sync Formulas from Latest Releases

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tap
        uses: actions/checkout@v3

      - name: Sync formulas from latest release tags
        run: |
          set -eux

          UPDATED=0

          git fetch --all
          git reset --hard origin/main

          for file in Formula/*.rb; do
            repo_name=$(basename "$file" .rb)

            # Get latest release tag
            latest_tag=$(curl -s "https://api.github.com/repos/adelynnmckay/$repo_name/releases/latest" | jq -r .tag_name)
            if [ "$latest_tag" = "null" ]; then
              echo "No release found for $repo_name"
              continue
            fi

            # Download the latest formula
            formula_url="https://raw.githubusercontent.com/adelynnmckay/$repo_name/$latest_tag/Formula/$repo_name.rb"
            curl -fsSL "$formula_url" -o "Formula/$repo_name.rb"

            # Get the corresponding tarball and compute SHA256
            tarball_url="https://github.com/adelynnmckay/$repo_name/archive/refs/tags/$latest_tag.tar.gz"
            sha=$(curl -sL "$tarball_url" | shasum -a 256 | cut -d' ' -f1)

            # Inject SHA256 into formula
            sed -i'' "s|^  sha256 \".*\"|  sha256 \"$sha\"|" "Formula/$repo_name.rb"

            # Check if file has changed
            if ! git diff --quiet -- "Formula/$repo_name.rb"; then
              echo "Formula for $repo_name updated"
              git add "Formula/$repo_name.rb"
              UPDATED=1
            else
              echo "No changes for $repo_name"
            fi
          done

          if [ "$UPDATED" -eq 1 ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git commit -m "Update formulas from latest tagged releases"
            git push
          else
            echo "All formulas are up to date."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
