name: Update Homebrew Tap

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tap
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl tar

      - name: Run update script
        run: bash scripts/update.sh
